import Header from "@/components/Header";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  // const indexError = Math.round(Math.random());

  // if (indexError === 0) {
  //   throw new Error("Artificial error!");
  // }

  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <footer>Next news exclusively for you since 1990.</footer>
      </body>
    </html>
  );
}
