import Header from "@/components/Header";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  setTimeout(() => {
    console.log("Page loaded");
  }, 10000);

  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <footer style={{ background: "DarkSeaGreen" }}>Footer</footer>
      </body>
    </html>
  );
}
